version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  basketapi:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"

  catalog.api:
    container_name: calatog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"    